### ISSUE TITLE
如何关闭？

### ISSUE THREAD

**Issue by WeiQLiu** [Yuphiz/RestartExplorer#1]
小白，请问vbs脚本直接双击打开后，不使用的话如何关闭？

**Comment by Yuphiz** [comment]
双击运行的不会在后台，一次性的

其他用法看readme的 [使用方法](https://github.com/Yuphiz/RestartExplorer?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

**Comment by WeiQLiu** [comment]
好的，感谢大佬
